from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QFileDialog
import os

class Ui_MainWindow(object):
    def __init__(self):
        self.pdfList = []

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(424, 672)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icon.ico"))
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 401, 641))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 8)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.queueList = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.queueList.setObjectName("queueList")
        self.verticalLayout_2.addWidget(self.queueList)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addPush = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addPush.setObjectName("addPush")

        

        self.horizontalLayout_2.addWidget(self.addPush)
        
       
        
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.removeList = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.removeList.setObjectName("removeList")
        self.removeList.setText("Remove List")
        self.verticalLayout_2.addWidget(self.removeList)

        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.qualityCombo = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.qualityCombo.setPlaceholderText("")
        self.qualityCombo.setObjectName("qualityCombo")
        self.verticalLayout_2.addWidget(self.qualityCombo)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setText("DPI")
        self.verticalLayout_2.addWidget(self.label_6)
        self.specifyDPI = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.specifyDPI.setMaximum(10000)
        self.specifyDPI.setValue(96)
        self.verticalLayout_2.addWidget(self.specifyDPI)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.outputPath = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.outputPath.setObjectName("outputPath")
        self.horizontalLayout.addWidget(self.outputPath)
        self.outPush = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.outPush.setObjectName("outPush")
        self.horizontalLayout.addWidget(self.outPush)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_5.addWidget(self.progressBar)
        self.exportPush = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.exportPush.setEnabled(True)
        self.exportPush.setMinimumSize(QtCore.QSize(0, 40))
        self.exportPush.setObjectName("exportPush")
        self.horizontalLayout_5.addWidget(self.exportPush)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        MainWindow.setCentralWidget(self.centralwidget)
